// Post-process Better Auth's `generate` output into a ZenStack shadow schema.
//
// Reads `zenstack/_ba-raw.prisma` (produced by `better-auth generate`) and
// emits `zenstack/_better-auth.zmodel` so ZenStack's policy engine can see
// BA's tables. Treats them as physically managed by BA — every model gets
// `@@ignore` so ZenStack will not generate CRUD helpers nor try to migrate.
//
// Why rename `User` → `BaUser` (and friends): keeps the BA namespace distinct
// from any future business model that might also be named `User`. The original
// table name is preserved via the existing `@@map("user")` directive.

import { readFileSync, unlinkSync, writeFileSync } from "node:fs";

const RAW = "zenstack/_ba-raw.prisma";
const OUT = "zenstack/_better-auth.zmodel";

const HEADER = `// AUTO-GENERATED by \`pnpm ba:shadow\`. DO NOT EDIT.
// Source: better-auth/cli generate from src/lib/auth/codegen.ts
// Regenerate after upgrading better-auth or changing additionalFields.
//
// All models here are physically managed by Better Auth (\`pnpm auth:migrate\`).
// Declared as @@ignore so ZenStack does not generate CRUD helpers, but their
// relations remain visible to the policy engine for cross-table reasoning.
`;

let src = readFileSync(RAW, "utf8");

// 1. Strip Prisma generator + datasource blocks — zmodel inherits these from
//    the main schema.zmodel via its own datasource directive.
src = src.replace(/^(generator|datasource)\s+\w+\s*\{[\s\S]*?^\}\s*/gm, "");

// 2. Discover model names in declaration order. Sort longest-first so
//    substring renames (e.g. `Team` inside `TeamMember`) cannot collide,
//    even though \b boundaries already prevent that — defense in depth.
const modelNames = [...src.matchAll(/^model\s+(\w+)\s*\{/gm)].map((m) => m[1]);
const sorted = [...modelNames].sort((a, b) => b.length - a.length);

// 3. Rename each model: declaration line + every field-type reference.
//    \b ensures we don't munge `userId`, `BaTeamMember`, `@@map("user")`, etc.
for (const name of sorted) {
	const pattern = new RegExp(`\\b${name}\\b`, "g");
	src = src.replace(pattern, `Ba${name}`);
}

// 4. Append @@ignore inside every model body (idempotent — skip if present).
src = src.replace(/(model\s+\w+\s*\{[\s\S]*?)(\n\})/g, (match, body, close) => {
	if (body.includes("@@ignore")) return match;
	return `${body}\n  @@ignore${close}`;
});

writeFileSync(OUT, `${HEADER}\n${src.trim()}\n`);
unlinkSync(RAW);

console.log(`✔ wrote ${OUT} (${modelNames.length} models)`);
